In [ ]:
import numpy as np

In [ ]:
def logic_gate(w1, w2, b):
    sigmoid = lambda x : 1/(1+np.exp(-x))
    return lambda x1, x2: sigmoid(w1 * x1 + w2 * x2 + b)

In [ ]:
def test(gate):
    for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
        print("{} , {} : {}".format(a, b, np.round(gate(a,b))))

In [ ]:
or_gate = logic_gate(20, 20, -10)
test(or_gate)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


In [ ]:
or_gate_01 = logic_gate(1,1,-0.5)
test(or_gate_01)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


# Part-II: Implement the operations of AND, NOR and NAND gates

### AND GATE

In [ ]:
and_gate = logic_gate(1,1,-1.5)
print("AND GATE \n")
test(and_gate)


AND GATE 

0 , 0 : 0.0
0 , 1 : 0.0
1 , 0 : 0.0
1 , 1 : 1.0


### NAND GATE

In [ ]:
nand_gate = logic_gate(-0.5,-0.5,0.7)
print("NAND GATE \n")
test(nand_gate)

NAND GATE 

0 , 0 : 1.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 0.0


### NOR GATE

In [ ]:
nor_gate = logic_gate(-1,-1,0.5)
print("NOR GATE \n")
test(nor_gate)

NOR GATE 

0 , 0 : 1.0
0 , 1 : 0.0
1 , 0 : 0.0
1 , 1 : 0.0



# Part-III: Limitations of single neuron for XOR operation

In [ ]:
xor = logic_gate(1,1,-0.5)
test(xor)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


# XOR Gate

In [ ]:
def xor(x1,x2):
    or_val = int(x1 or x2)
    and_val = int(not(x1 and x2))
    xor_val = int(or_val and and_val)
    return xor_val

In [ ]:
test(xor)

0 , 0 : 0
0 , 1 : 1
1 , 0 : 1
1 , 1 : 0


# Part-IV: Logic Gates using Keras library

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Function to create and run the model
def run_logic_gate_model(gate_name, x_train, y_train):
    # Create the model
    model = Sequential()
    model.add(Dense(16, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])

    # Train the model
    model.fit(x_train, y_train, epochs=100, verbose=0)

    # Predict the output values
    predictions = model.predict(x_train)
    predictions = np.round(predictions)

    # Print the predictions
    print(f"{gate_name} Gate Predictions:")
    print(predictions.flatten().astype(int))
    print()


In [ ]:

# Input and output values for the logic gates
input_values = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# AND gate
and_output = np.array([0, 0, 0, 1])
run_logic_gate_model("AND", input_values, and_output)

# OR gate
or_output = np.array([0, 1, 1, 1])
run_logic_gate_model("OR", input_values, or_output)

# NOT gate
not_output = np.array([1, 0, 1, 0])
run_logic_gate_model("NOT", input_values, not_output)

# NAND gate
nand_output = np.array([1, 1, 1, 0])
run_logic_gate_model("NAND", input_values, nand_output)

# NOR gate
nor_output = np.array([1, 0, 0, 0])
run_logic_gate_model("NOR", input_values, nor_output)

# XOR gate
xor_output = np.array([0, 1, 1, 0])
run_logic_gate_model("XOR", input_values, xor_output)


1/1 [==============================] - 0s 79ms/step
AND Gate Predictions:
[0 0 0 1]

1/1 [==============================] - 0s 60ms/step
OR Gate Predictions:
[1 1 1 1]

1/1 [==============================] - 0s 63ms/step
NOT Gate Predictions:
[1 0 0 0]

1/1 [==============================] - 0s 52ms/step
NAND Gate Predictions:
[1 1 1 0]



1/1 [==============================] - 0s 54ms/step
NOR Gate Predictions:
[0 0 0 0]



1/1 [==============================] - 0s 85ms/step
XOR Gate Predictions:
[1 0 1 0]



In [4]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Step 1: Create input and output data using NumPy arrays

# Define the input data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Step 2: Create neural network models for each logic gate

def create_logic_gate_model():
    model = Sequential()
    model.add(Dense(16, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    return model

# Logic Gates Implementation

# AND Gate
Y_AND = np.array([0, 0, 0, 1])

# OR Gate
Y_OR = np.array([0, 1, 1, 1])

# NOT Gate
Y_NOT = np.array([1, 0])

# NAND Gate
Y_NAND = np.array([1, 1, 1, 0])

# NOR Gate
Y_NOR = np.array([1, 0, 0, 0])

# XOR Gate
Y_XOR = np.array([0, 1, 1, 0])

# Create models for each gate
and_model = create_logic_gate_model()
or_model = create_logic_gate_model()

nand_model = create_logic_gate_model()
nor_model = create_logic_gate_model()
xor_model = create_logic_gate_model()

# Compile models
and_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
or_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

nand_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
nor_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
xor_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train models for each gate
and_model.fit(X, Y_AND, epochs=1000, verbose=0)
or_model.fit(X, Y_OR, epochs=1000, verbose=0)

nand_model.fit(X, Y_NAND, epochs=1000, verbose=0)
nor_model.fit(X, Y_NOR, epochs=1000, verbose=0)
xor_model.fit(X, Y_XOR, epochs=1000, verbose=0)

# Evaluate the models
loss_and, accuracy_and = and_model.evaluate(X, Y_AND)
loss_or, accuracy_or = or_model.evaluate(X, Y_OR)

loss_nand, accuracy_nand = nand_model.evaluate(X, Y_NAND)
loss_nor, accuracy_nor = nor_model.evaluate(X, Y_NOR)
loss_xor, accuracy_xor = xor_model.evaluate(X, Y_XOR)

# Print the results
print("AND Gate:")
print(f"Loss: {loss_and:.4f}, Accuracy: {accuracy_and:.4f}")

print("\nOR Gate:")
print(f"Loss: {loss_or:.4f}, Accuracy: {accuracy_or:.4f}")

print("\nNAND Gate:")
print(f"Loss: {loss_nand:.4f}, Accuracy: {accuracy_nand:.4f}")

print("\nNOR Gate:")
print(f"Loss: {loss_nor:.4f}, Accuracy: {accuracy_nor:.4f}")

print("\nXOR Gate:")
print(f"Loss: {loss_xor:.4f}, Accuracy: {accuracy_xor:.4f}")


1/1 [==============================] - 0s 113ms/step - loss: 0.0881 - accuracy: 1.0000
AND Gate:
Loss: 0.0364, Accuracy: 1.0000

OR Gate:
Loss: 0.1688, Accuracy: 1.0000

NAND Gate:
Loss: 0.0335, Accuracy: 1.0000

NOR Gate:
Loss: 0.1347, Accuracy: 1.0000

XOR Gate:
Loss: 0.0881, Accuracy: 1.0000


In [7]:
# Input data for XOR gate
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Predict XOR gate outputs
predictions_xor = xor_model.predict(X_xor)

# Print the predictions
for i in range(len(X_xor)):
    input_data = X_xor[i]
    predicted_output = predictions_xor[i][0]
    print(f"Input: {input_data}, Predicted Output: {round(predicted_output)}")


1/1 [==============================] - 0s 47ms/step
Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 1
Input: [1 0], Predicted Output: 1
Input: [1 1], Predicted Output: 0
